<?php
/* @var $this Web4pro_Googlemerchants_Block_Adminhtml_Editfeed_Edit_Form */
?>
<div id="edit_form_wrap" class="entity-edit">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4><?php echo $this->__('Manage google feed') ?></h4>
        </div>
    </div>
    <form id="edit_form" method="post" action="<?php echo $this->getSaveUrl() ?>">
        <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>"/>

        <div class="box">
            <div class="hor-scroll">
                <table cellspacing="0" cellpadding="0" class="dynamic-grid" style="width:70%;" align="center">
                    <thead>
                    <tr class="headings">
                        <th style="width:160px;"><?php echo $this->__('Field Name') ?></th>
                        <th width="40%"><?php echo $this->__('Value') ?></th>
                        <th style="width:40%;"><?php echo $this->__('Action') ?></th>
                    </tr>
                    </thead>
                    <tbody id="mapping-table-body">
                    <?php echo $this->getTableBodyHtml() ?>
                    </tbody>
                </table>
                </br>
                <button id="add_row_btn" onclick="addRow();return false;" class="scalable add" title="Add Option">
                    <span>Add Option</span>
                </button>
            </div>
        </div>
    </form>

    <script type="text/javascript">
        var lastIndex = getLastIndex();

        function removeRow(index) {
            var elementForDelete = $('table-row-' + index);
            if (elementForDelete != null) {
                elementForDelete.remove();
            }
        }
        function addRow() {
            var indexTAppend = lastIndex + 1;
            var rowHtml = '<tr id="table-row-' + indexTAppend + '"><td><input name="feed-col-name[' + indexTAppend + ']"/></td>';
            rowHtml += '<td><select name="attribute-select[' + indexTAppend + ']">';
            rowHtml += '<?php echo $this->getOptionsHtml()?>';
            rowHtml += '</select></td>';
            rowHtml += '<td><button onclick="removeRow(' + indexTAppend + ');return false;">Remove</button></td>';
            var lastRowId = "table-row-" + lastIndex;
            var elementToAppend = $(lastRowId);
            if (elementToAppend != null) {
                $(lastRowId).insert({after: rowHtml});
                lastIndex++;
            }
        }
        function getLastIndex() {
            var trs = $('mapping-table-body').getElementsByTagName("tr");
            var lastEl = trs[trs.length - 1];
            var lastElId = lastEl.id;
            var laseFreeNum = lastElId.replace('table-row-', '');
            return parseInt(laseFreeNum);
        }

    </script>
</div>
</div>