<?php
/* @var $this Web4pro_Googlemerchants_Block_Adminhtml_Editfeed_Edit_Form */
?>
<div id="edit_form_wrap" class="entity-edit">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4><?php echo $this->__('Manage google feed')?></h4>
        </div>
    </div>
    <form id="edit_form" method="post" action="<?php echo $this->getSaveUrl() ?>">
        <input name="form_key" type="hidden" value="<?php echo $this->getFormKey()?>" />

        <div class="box">
            <div class="hor-scroll">
              <?php /*  <div>
                    <?php $availableStores = $this->getAvailableStores();?>
                    <label for="select_store_name"><?php echo $this->__('Please choose the store view for generating feed:'); ?></label>
                    <select name="select_store_name">
                        <?php foreach($availableStores as $store):?>
                            <option value="<?php echo $store['value']?>"><?php echo $store['label']?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
              */ ?>
                <table cellspacing="0" cellpadding="0" class="dynamic-grid" style="width:100%;" align="center">
                    <thead>
                    <tr class="headings">
                        <th style="width:160px;"><?php echo $this->__('Field Name')?></th>
                        <th width="40%"><?php echo $this->__('Prefix')?></th>
                        <th width="40%"><?php echo $this->__('Value for Google Feed')?></th>
                        <th width="40%"><?php echo $this->__('Postfix')?></th>
                        <th style="width:40%;"><?php echo $this->__('Action')?></th>
                    </tr>
                    </thead>
                    <tbody id="mapping-table-body">
                        <?php echo $this->getTableBodyHtml() ?>
                    </tbody>
                </table>
                </br>
                <button id="add_row_btn" onclick="addRow();return false;" class="scalable add" title="Add Option">
                    <span>Add Option</span>
                </button>
            </div>
        </div>
    </form>

    <script type="text/javascript">
        var lastIndex = getLastIndex();

        function removeRow(index) {
            var currentRow = $('table-row-' + index);
            var currentSelects = $$('#table-row-' + index + ' .required-entry');
            for(i = 0; i < currentSelects.length; i ++){
                currentSelects[i].setAttribute('disabled', 'disabled');
            }

            var currentPrefixInputs = $$('#table-row-' + index + ' .prefix-postfix-input-field');
            for(i = 0; i < currentPrefixInputs.length; i ++){
                currentPrefixInputs[i].setAttribute('disabled', 'disabled');
            }

            currentRow.hide();
            lastIndex = getLastIndex();
        }

        function addRow()
        {
            var indexTAppend = lastIndex + 1;
            var rowHtml = '<tr id="table-row-' + indexTAppend + '" class="table-row-googlefeed"><td><input name="feed-col-name[' + indexTAppend + ']" class="required-entry"/></td>';
            rowHtml += '<td><input name="feed-pref-name[' + indexTAppend + ']" class="prefix-postfix-input-field"/></td>';
            rowHtml += '<td><select name="attribute-select[' + indexTAppend + ']" class="required-entry select select-googlefeed">';
            rowHtml += '<?php echo $this->getOptionsHtml()?>';
            rowHtml += '</select></td>';
            rowHtml += '<td><input name="feed-postf-name[' + indexTAppend + ']" class="prefix-postfix-input-field"/></td>';
            rowHtml += '<td><button type="button" onclick="removeRow(' + indexTAppend + ');" class="delete delete-option">Remove</button></td>';
            var lastRowId = "table-row-" + lastIndex;
            var elementToAppend = $(lastRowId);
            if(elementToAppend != null)
            {
                $(lastRowId).insert({after:rowHtml});
                lastIndex++;
            }
        }
        function getLastIndex()
        {
            return $('mapping-table-body').getElementsByTagName("tr").length - 1;
        }

    </script>
</div>
